### PR TITLE
Add R 3.5.1 builds for ggplot2 v2.2.1

### PR DESCRIPTION
**Pull request by halldc**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

- Build number is 1, because v2.2.1 package already exists
- Should go in a `v2.2.1` branch (not merge into the master branch)
- Needed to get `rpy2` working with R 3.5.1 (https://github.com/conda-forge/rpy2-feedstock/pull/10)

### CODE REVIEW

**Comment by halldc** [comment]
@conda-forge-admin, please rerender

**Comment by nsoranzo** [comment]
@halldc Since this is presently targeting the `master` branch, can you add something like `[WIP]` to the PR title?

**Comment by halldc** [comment]
@nsoranzo Sure - I wasn't able to make it target a new branch (this probably requires write permissions).

**Comment by ocefpaf** [comment]
> I wasn't able to make it target a new branch (this probably requires write permissions).

Done :wink:

**Pull request merged**
